### ISSUE TITLE
[Improvement] Link to your github profile on `Follow Me` is missing

### ISSUE THREAD

**Issue by iatharva** [tianmai1/tianmai1.github.io#1]
I think you forgot to add a link i.e. `https://github.com/tianmai1/` to your Github profile on the `Follow me` button and the current link on it takes you to `https://github.com/xxxxxx`

Additionally, if you want to achieve something like giving an option to follow/sponsor/watch/star etc [this ](https://buttons.github.io/) might help you

**Comment by tianmai1** [comment]
Thanks, it's been changed

**Comment by tianmai1** [comment]
呜呜呜
